---
ruby_dependencies:
  - libreadline-dev
  - libssl-dev
  - libyaml-dev
  - zlib1g-dev

ruby_symlinks:
  - bundle
  - erb
  - gem
  - irb
  - rake
  - rdoc
  - ri
  - ruby
  - testrb

ruby_location: "/opt/{{ ruby_version }}"
